<a href="https://colab.research.google.com/github/Balasriradhagunnam/MLWorkShop/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment - I


##Q1.Perform arithmetic operations on NumPy arrays.


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,3,5],[2,4,6]])
print("---ADDITION---")
print(f"First method {a+b}") #1st Method
print(f"Second Method {np.add(a,b)}") #2nd Method
print("---SUBTRACTION---")
print(f"First method {a-b}") #1st Method
print(f"Second Method {np.subtract(a,b)}") #2nd Method
print("---MULTIPLICATION---")
print(f"First method {a*b}") #1st Method
print(f"Second Method {np.multiply(a,b)}") #2nd Method
print("---DIVISION---")
print(f"First method {a/b}") #1st Method
print(f"Second Method {np.divide(a,b)}") #2nd Method
print("---FLOOR DIVISION---")
print(f"First method {a//b}") #1st Method
print(f"Second Method {np.floor_divide(a,b)}") #2nd Method
print("---MODULUS---")
print(f"First method {a%b}") #1st Method
print(f"Second Method {np.mod(a,b)}") #2nd Method
print("---EXPONENTIAL---")
print(f"First method {a**b}") #1st Method
print(f"Second Method {np.power(a,b)}") #2nd Method
print("---SQUARE ROOT---")
print(f"First method {np.sqrt(a)}") #1st Method
print(f"Second Method {np.sqrt(b)}") #2nd Method

---ADDITION---
First method [[ 2  5  8]
 [ 6  9 12]]
Second Method [[ 2  5  8]
 [ 6  9 12]]
---SUBTRACTION---
First method [[ 0 -1 -2]
 [ 2  1  0]]
Second Method [[ 0 -1 -2]
 [ 2  1  0]]
---MULTIPLICATION---
First method [[ 1  6 15]
 [ 8 20 36]]
Second Method [[ 1  6 15]
 [ 8 20 36]]
---DIVISION---
First method [[1.         0.66666667 0.6       ]
 [2.         1.25       1.        ]]
Second Method [[1.         0.66666667 0.6       ]
 [2.         1.25       1.        ]]
---FLOOR DIVISION---
First method [[1 0 0]
 [2 1 1]]
Second Method [[1 0 0]
 [2 1 1]]
---MODULUS---
First method [[0 2 3]
 [0 1 0]]
Second Method [[0 2 3]
 [0 1 0]]
---EXPONENTIAL---
First method [[    1     8   243]
 [   16   625 46656]]
Second Method [[    1     8   243]
 [   16   625 46656]]
---SQUARE ROOT---
First method [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Second Method [[1.         1.73205081 2.23606798]
 [1.41421356 2.         2.44948974]]


##Q2.Write a script to compute the mean and standard deviation of a NumPy array.

* Mean=Sum of all observations/no.of observations
* Standard Deviation=sqrt(Σ(element-mean)^2/no.ofobservations-1)


In [ ]:
import numpy as np
ele=np.array([10,8,10,8,8,4])
print(f"Mean of array {int(np.mean(ele))}")
print(f"Standard Deviation of array {int(np.std(ele))}")

Mean of array 8
Standard Deviation of array 2


##Q3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
import numpy as np
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


##Q4.Reshape the array into a 2x4 matrix

In [ ]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
print(a)
print(f"Shape of array is {a.shape}")
b=[0,1,2,1]
c=a[:,b]
print(c)
print(f"Shape of Updated array is {c.shape}")

[[1 2 3]
 [3 4 5]]
Shape of array is (2, 3)
[[1 2 3 2]
 [3 4 5 4]]
Shape of Updated array is (2, 4)


##Q5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
* Extract the sub-matrix containing the last two rows and first two columns.
* Replace all elements greater than 4 with 0.

In [189]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
sub=arr[1:,:2]
print("Sub-array is ")
print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-array is 
[[4 5]
 [7 8]]


In [ ]:
import numpy as np
a=np.array([1,5,10,20,2])
print(f"Original array is {a}")
a[a>4]=0
print(f"Replaced Array is {a}")

Original array is [ 1  5 10 20  2]
Replaced Array is [1 0 0 0 2]


##Q6.Create two 1D arrays:
* a = np.array([1, 2, 3])

* b = np.array([4, 5, 6])

* Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"Addition of array is {a+b}")
print(f"Multiplication of array is {a*b}")
print(f"Division of array is {a/b}")

Addition of array is [5 7 9]
Multiplication of array is [ 4 10 18]
Division of array is [0.25 0.4  0.5 ]


##Q7.Create a random NumPy array of size (4, 4). Compute:
* Mean of each column.
* Maximum value of the entire array.
* Sum of all elements.

In [ ]:
import numpy as np
a=np.random.randint(0,11,size=(4,4))
print("Random Numpy Array")
print(a)
print(f"Mean of each column {np.mean(a,axis=0)}")
print(f"Maximum value of the entire array {np.max(a)}")
print(f"Sum of all elements {np.sum(a)}")

Random Numpy Array
[[ 2  1  7  4]
 [ 9  9  1  5]
 [ 2 10  5 10]
 [ 5  9  4  6]]
Mean of each column [4.5  7.25 4.25 6.25]
Maximum value of the entire array 10
Sum of all elements 89


##Q8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(f"Actual array is {arr}")
b=(arr+10)*2
print(f"Updated array is {b}")

Actual array is [1 2 3 4]
Updated array is [22 24 26 28]


##Q9.Perform advanced slicing and indexing on a 3D array.
###Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
* Extract the second "layer" (i.e., the second 2D array) in the first dimension.
* Extract the first two rows and the last three columns from each "layer."
* Replace all elements divisible by 3 with -1.


In [ ]:
import numpy as np
arr=np.random.randint(1,101,size=(3,4,5))
print("---Actual Array is---")
print(arr)
print("---the second 2D array---")
a=arr[1,:,:]
print(a)
print("---the first two rows and the last three columns---")
b=arr[:,:2,-3:]
print(b)
arr[arr%3==0]=-1
print("---Array after replacing the elements with -1 which are perfectly divisibe by 3---")
print(arr)

---Actual Array is---
[[[ 86  83  59  77  47]
  [  6  86  25  42  56]
  [ 75  15  88  20  20]
  [  5   7  52  17   6]]

 [[ 23  56  44  46  76]
  [ 80  69  50  41  71]
  [ 19  96   4  11  71]
  [ 77  44  93  27  30]]

 [[  5  52  84  38  76]
  [ 80   5  67 100  71]
  [ 75  11  92  80  81]
  [ 20  24  16  69  58]]]
---the second 2D array---
[[23 56 44 46 76]
 [80 69 50 41 71]
 [19 96  4 11 71]
 [77 44 93 27 30]]
---the first two rows and the last three columns---
[[[ 59  77  47]
  [ 25  42  56]]

 [[ 44  46  76]
  [ 50  41  71]]

 [[ 84  38  76]
  [ 67 100  71]]]
---Array after replacing the elements with -1 which are perfectly divisibe by 3---
[[[ 86  83  59  77  47]
  [ -1  86  25  -1  56]
  [ -1  -1  88  20  20]
  [  5   7  52  17  -1]]

 [[ 23  56  44  46  76]
  [ 80  -1  50  41  71]
  [ 19  -1   4  11  71]
  [ 77  44  -1  -1  -1]]

 [[  5  52  -1  38  76]
  [ 80   5  67 100  71]
  [ -1  11  92  80  -1]
  [ 20  -1  16  -1  58]]]


##Q10.Work with broadcasting and advanced operations in NumPy.
##Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20. Perform the following:
* Subtract the mean of each row from its respective elements (row-wise
normalization).
* Create a new array by squaring all the elements in arr.
* Find the indices of the top 3 maximum values in the entire array.

In [ ]:
import numpy as np
arr=np.random.randint(1,21,size=(3,3))
print("---Actual Array is---")
print(arr)
print("---Subtract the mean of each row from its respective elements (row-wise normalization)---")
a=arr-arr.mean(axis=1)
print(a)
print("---Create a new array by squaring all the elements in arr---")
b=[np.sqrt(arr)]
print(b)
print("---Find the indices of the top 3 maximum values in the entire array---")
flat_indices = np.argsort(arr.ravel())[-3:]
top_3_indices = np.unravel_index(flat_indices, arr.shape)
print("Indices of the top 3 elements in descending order:")
top_3_indices = list(zip(top_3_indices[0], top_3_indices[1]))
print(top_3_indices)

---Actual Array is---
[[13 13  5]
 [ 2  8 13]
 [15 15  7]]
---Subtract the mean of each row from its respective elements (row-wise normalization)---
[[ 2.66666667  5.33333333 -7.33333333]
 [-8.33333333  0.33333333  0.66666667]
 [ 4.66666667  7.33333333 -5.33333333]]
---Create a new array by squaring all the elements in arr---
[array([[3.60555128, 3.60555128, 2.23606798],
       [1.41421356, 2.82842712, 3.60555128],
       [3.87298335, 3.87298335, 2.64575131]])]
---Find the indices of the top 3 maximum values in the entire array---
Indices of the top 3 elements in descending order:
[(1, 2), (2, 0), (2, 1)]
